// ── Generated by UIPilot — safe to edit ────────────────────
// This file was created by UIPilot but belongs to you.
// Once you edit it, UIPilot asks before it ever overwrites it.
// A menu you build later only adds its own methods at the end.
// ─────────────────────────────────────────────────────────────

using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

public class UIPilot_GameManager : MonoBehaviour
{
    private const string MainMenuPanel = "UIPilot_MainMenu_Panel";
    private const string PauseMenuPanel = "UIPilot_PauseMenu_Panel";
    private const string SettingsPanel = "UIPilot_Settings_Panel";
    private const string QuitButton = "UIPilot_Btn_Quit";

    // Settings are remembered between runs under these PlayerPrefs keys.
    private const string VolumeKey = "UIPilot.Volume";
    private const string FullscreenKey = "UIPilot.Fullscreen";
    private const string QualityKey = "UIPilot.Quality";

    private GameObject _mainMenuPanelGO;
    private GameObject _pauseMenuPanelGO;
    private GameObject _settingsPanelGO;
    private string _currentPanel;
    private string _settingsReturnPanel = MainMenuPanel;

    private float _volume;
    private bool _fullscreen;
    private int _quality;
    private TMP_Text _volumeValue;
    private RectTransform _volumeFill;
    private TMP_Text _fullscreenValue;
    private TMP_Text _qualityValue;

    // While paused: the cursor as the game had it, put back on Resume.
    private bool _paused;
    private CursorLockMode _cursorLockBeforePause;
    private bool _cursorVisibleBeforePause;

    // While Quit is asking: what had focus when it asked, its label,
    // what the label said, and until when.
    private GameObject _quitFocus;
    private TMP_Text _quitLabel;
    private string _quitWord;
    private float _quitAskedUntil;

    [Header("Play")]
    [Tooltip("The scene the Play button loads: a name or path from the scene list in File > Build Profiles. Empty = Play hides the menu and the game starts in this scene.")]
    public string gameScene = "";

    [Header("Scene")]
    [Tooltip("The hour the menu's scene shows, for themes that have one: 0 = midnight, 0.25 = dawn, 0.5 = noon, 0.75 = dusk. Change it from your code with SetTimeOfDay.")]
    [Range(0f, 1f)] public float timeOfDay = 0.5f;

    [Tooltip("Seconds for one full day, when the scene should run on its own. 0 = it stays at Time Of Day.")]
    public float dayLengthSeconds = 0f;

    // The one value every scene layer reads; UIPilot's shader looks it up by this name.
    private const string TimeOfDayProperty = "_UIPilotTimeOfDay";
    private float _hourFrom, _hourStep, _hourBlend = 1f, _hourSeconds;

    private void Awake()
    {
        Shader.SetGlobalFloat(TimeOfDayProperty, timeOfDay);

        _mainMenuPanelGO = FindObject(MainMenuPanel);
        _pauseMenuPanelGO = FindObject(PauseMenuPanel);
        _settingsPanelGO = FindObject(SettingsPanel);

        _volumeValue = FindText("UIPilot_Settings_VolumeValue");
        _fullscreenValue = FindText("UIPilot_Settings_FullscreenValue");
        _qualityValue = FindText("UIPilot_Settings_QualityValue");

        var fill = FindObject("UIPilot_Settings_VolumeFill");
        _volumeFill = fill != null ? fill.GetComponent<RectTransform>() : null;

        // The main menu's small print always shows the build's real version.
        var version = FindText("UIPilot_MainMenu_Footnote");
        if (version != null) version.text = string.Format("Version {0}", Application.version);

        _volume = PlayerPrefs.GetFloat(VolumeKey, AudioListener.volume);
        _fullscreen = PlayerPrefs.GetInt(FullscreenKey, Screen.fullScreen ? 1 : 0) == 1;
        _quality = PlayerPrefs.GetInt(QualityKey, QualitySettings.GetQualityLevel());
        ApplySettings();
    }

    // Start, not Awake: the EventSystem must be running before a button can take focus.
    // A scene with a main menu opens on it; a game scene with only a pause menu starts in play.
    private void Start()
    {
        ShowPanel(_mainMenuPanelGO != null ? MainMenuPanel : string.Empty);
    }

    private void Update()
    {
        TurnClock();

        if (PausePressed()) OnPauseKey();
        else if (BackPressed()) GoBack();

        if (_quitLabel != null && (Time.unscaledTime > _quitAskedUntil || FocusMovedOn()))
            StopAskingToQuit();
    }

    // Leaving the scene while paused must not leave the next one frozen.
    private void OnDestroy()
    {
        if (_paused) Time.timeScale = 1f;
    }

    // Turns the scene's clock: a running day, or one blend asked for by SetTimeOfDay.
    // Unscaled time, so the scene keeps moving behind a pause menu.
    private void TurnClock()
    {
        if (dayLengthSeconds > 0f)
        {
            timeOfDay = Mathf.Repeat(timeOfDay + Time.unscaledDeltaTime / dayLengthSeconds, 1f);
            _hourBlend = 1f;
        }
        else if (_hourBlend < 1f)
        {
            _hourBlend = Mathf.Min(1f, _hourBlend + Time.unscaledDeltaTime / _hourSeconds);
            var eased = _hourBlend * _hourBlend * (3f - 2f * _hourBlend);
            timeOfDay = Mathf.Repeat(_hourFrom + _hourStep * eased, 1f);
        }

        Shader.SetGlobalFloat(TimeOfDayProperty, timeOfDay);
    }

    // Sets the scene's hour (0 = midnight, 0.5 = noon), at once or blended over
    // some seconds, the short way round the clock. Call it from your own code:
    // FindAnyObjectByType<UIPilot_GameManager>().SetTimeOfDay(0.75f, 3f);
    public void SetTimeOfDay(float hour, float seconds = 0f)
    {
        hour = Mathf.Repeat(hour, 1f);
        if (seconds <= 0f)
        {
            timeOfDay = hour;
            _hourBlend = 1f;
            Shader.SetGlobalFloat(TimeOfDayProperty, timeOfDay);
            return;
        }

        _hourFrom = timeOfDay;
        _hourStep = Mathf.Repeat(hour - timeOfDay + 0.5f, 1f) - 0.5f;
        _hourSeconds = seconds;
        _hourBlend = 0f;
    }

    // Finds an object even when it, or its panel, is switched off.
    private static GameObject FindObject(string objectName)
    {
        var found = GameObject.Find(objectName);
        if (found != null) return found;

        foreach (var candidate in Resources.FindObjectsOfTypeAll<GameObject>())
            if (candidate.name == objectName && candidate.scene.IsValid())
                return candidate;

        return null;
    }

    private static TMP_Text FindText(string objectName)
    {
        var found = FindObject(objectName);
        return found != null ? found.GetComponent<TMP_Text>() : null;
    }

    public void ShowPanel(string panelName)
    {
        StopAskingToQuit();

        if (_mainMenuPanelGO != null)
            _mainMenuPanelGO.SetActive(panelName == MainMenuPanel);

        if (_pauseMenuPanelGO != null)
            _pauseMenuPanelGO.SetActive(panelName == PauseMenuPanel);

        if (_settingsPanelGO != null)
            _settingsPanelGO.SetActive(panelName == SettingsPanel);

        _currentPanel = panelName;
        FocusFirstButton();
    }

    // Keyboard and gamepad players need a starting point, so the first button
    // of whichever panel is showing takes focus. Mouse players are unaffected.
    private void FocusFirstButton()
    {
        var eventSystem = UnityEngine.EventSystems.EventSystem.current;
        if (eventSystem == null) return;

        var panel = CurrentPanelObject();
        var first = panel != null ? panel.GetComponentInChildren<UnityEngine.UI.Button>() : null;
        eventSystem.SetSelectedGameObject(first != null ? first.gameObject : null);
    }

    private GameObject CurrentPanelObject()
    {
        if (_currentPanel == MainMenuPanel) return _mainMenuPanelGO;
        if (_currentPanel == PauseMenuPanel) return _pauseMenuPanelGO;
        if (_currentPanel == SettingsPanel) return _settingsPanelGO;
        return null;
    }

    // Esc, or Start on a gamepad.
    private static bool PausePressed()
    {
#if ENABLE_INPUT_SYSTEM
        var keyboard = Keyboard.current;
        var gamepad = Gamepad.current;
        return (keyboard != null && keyboard.escapeKey.wasPressedThisFrame)
            || (gamepad != null && gamepad.startButton.wasPressedThisFrame);
#else
        return Input.GetKeyDown(KeyCode.Escape);
#endif
    }

    // B on an Xbox pad, Circle on a PlayStation pad: the button Unity's UI treats as Cancel.
    private static bool BackPressed()
    {
#if ENABLE_INPUT_SYSTEM
        var gamepad = Gamepad.current;
        return gamepad != null && gamepad.buttonEast.wasPressedThisFrame;
#else
        return Input.GetKeyDown(KeyCode.JoystickButton1);
#endif
    }

    // In play, the pause key opens the pause menu, if this scene has one.
    // In a menu it goes back, like B.
    private void OnPauseKey()
    {
        if (!string.IsNullOrEmpty(_currentPanel)) GoBack();
        else if (_pauseMenuPanelGO != null) OpenPauseMenu();
    }

    // One step out of whatever is showing. The main menu has nowhere to go back to.
    private void GoBack()
    {
        if (_quitLabel != null) StopAskingToQuit();
        else if (_currentPanel == SettingsPanel) ShowPanel(_settingsReturnPanel);
        else if (_currentPanel == PauseMenuPanel) ResumeGame();
    }

    // Stops time and frees the cursor, which a camera or shooter script may have locked.
    // Call it from your own code too, for example when the game window loses focus.
    public void OpenPauseMenu()
    {
        if (_pauseMenuPanelGO == null) return;

        if (!_paused)
        {
            _paused = true;
            _cursorLockBeforePause = Cursor.lockState;
            _cursorVisibleBeforePause = Cursor.visible;
        }

        Cursor.lockState = CursorLockMode.None;
        Cursor.visible = true;
        Time.timeScale = 0f;
        ShowPanel(PauseMenuPanel);
    }

    // Back to the game: time runs again, and the cursor is as the game left it.
    private void ResumeGame()
    {
        Time.timeScale = 1f;
        if (_paused)
        {
            _paused = false;
            Cursor.lockState = _cursorLockBeforePause;
            Cursor.visible = _cursorVisibleBeforePause;
        }

        ShowPanel(string.Empty);
    }

    // Quit asks once: its label changes for three seconds, and a second press quits.
    // Returns false when this panel has no Quit button to ask with.
    private bool AskToQuit()
    {
        var panel = CurrentPanelObject();
        if (panel == null) return false;

        foreach (var button in panel.GetComponentsInChildren<UnityEngine.UI.Button>())
        {
            if (button.name != QuitButton) continue;

            var label = button.GetComponentInChildren<TMP_Text>();
            if (label == null) return false;

            _quitFocus = Selected();
            _quitLabel = label;
            _quitWord = label.text;
            _quitAskedUntil = Time.unscaledTime + 3f;
            label.text = "Press again to quit";
            return true;
        }

        return false;
    }

    private void StopAskingToQuit()
    {
        if (_quitLabel != null) _quitLabel.text = _quitWord;
        _quitLabel = null;
        _quitFocus = null;
    }

    // Quit's question ends when focus moves to another control. A click on
    // empty space selects nothing, and keeps the question up.
    private bool FocusMovedOn()
    {
        var selected = Selected();
        return selected != null && selected != _quitFocus;
    }

    // What has keyboard and gamepad focus.
    private static GameObject Selected()
    {
        var eventSystem = UnityEngine.EventSystems.EventSystem.current;
        return eventSystem != null ? eventSystem.currentSelectedGameObject : null;
    }

    // Clamps, applies, saves and displays the three settings. Every settings
    // button changes one value and then calls this.
    private void ApplySettings()
    {
        var qualityNames = QualitySettings.names;
        _volume = Mathf.Clamp01(Mathf.Round(_volume * 10f) / 10f);
        _quality = Mathf.Clamp(_quality, 0, Mathf.Max(0, qualityNames.Length - 1));

        AudioListener.volume = _volume;
        Screen.fullScreen = _fullscreen;
        if (QualitySettings.GetQualityLevel() != _quality)
            QualitySettings.SetQualityLevel(_quality);

        PlayerPrefs.SetFloat(VolumeKey, _volume);
        PlayerPrefs.SetInt(FullscreenKey, _fullscreen ? 1 : 0);
        PlayerPrefs.SetInt(QualityKey, _quality);

        if (_volumeValue != null) _volumeValue.text = Mathf.RoundToInt(_volume * 100f) + "%";
        if (_volumeFill != null) _volumeFill.anchorMax = new Vector2(_volume, 1f);
        if (_fullscreenValue != null) _fullscreenValue.text = _fullscreen ? "On" : "Off";
        if (_qualityValue != null && qualityNames.Length > 0) _qualityValue.text = qualityNames[_quality];
    }

    public void OnPlayPressed()
    {
        // Game Scene set: load it. Empty: hide the menu, and the game starts in this scene.
        if (string.IsNullOrEmpty(gameScene))
        {
            ShowPanel(string.Empty);
            return;
        }

        if (!Application.CanStreamedLevelBeLoaded(gameScene))
        {
            Debug.LogWarning("UIPilot: Play can't load \"" + gameScene + "\". Add it to the scene list in File > Build Profiles.");
            return;
        }

        SceneManager.LoadScene(gameScene);
    }

    public void OnSettingsPressed()
    {
        if (_settingsPanelGO == null)
        {
            Debug.LogWarning("UIPilot: this scene has no Settings panel. Tick Settings Menu in Tools > UIPilot, then click Build UI.");
            return;
        }

        _settingsReturnPanel = _currentPanel == SettingsPanel ? MainMenuPanel : _currentPanel;
        ShowPanel(SettingsPanel);
    }

    public void OnQuitPressed()
    {
        // The first press asks (the label changes); a second press quits.
        if (_quitLabel == null && AskToQuit()) return;

#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }

    public void OnResumePressed()
    {
        ResumeGame();
    }

    public void OnVolumeDownPressed()
    {
        _volume -= 0.1f;
        ApplySettings();
    }

    public void OnVolumeUpPressed()
    {
        _volume += 0.1f;
        ApplySettings();
    }

    public void OnFullscreenPressed()
    {
        _fullscreen = !_fullscreen;
        ApplySettings();
    }

    public void OnQualityDownPressed()
    {
        _quality--;
        ApplySettings();
    }

    public void OnQualityUpPressed()
    {
        _quality++;
        ApplySettings();
    }

    public void OnBackPressed()
    {
        ShowPanel(_settingsReturnPanel);
    }
}
