// ── Generated by UIPilot — safe to edit ────────────────────
// This file was created by UIPilot but belongs to you.
// UIPilot will not overwrite your changes on regenerate
// unless you run Quick Clear first.
// ─────────────────────────────────────────────────────────────

using UnityEngine;

public class UIPilot_GameManager : MonoBehaviour
{
    private const string MainMenuPanel = "UIPilot_MainMenu_Panel";
    private const string PauseMenuPanel = "UIPilot_PauseMenu_Panel";
    private const string SettingsPanel = "UIPilot_Settings_Panel";

    private GameObject _mainMenuPanelGO;
    private GameObject _pauseMenuPanelGO;
    private GameObject _settingsPanelGO;
    private string _currentPanel;
    private string _settingsReturnPanel = MainMenuPanel;

    private void Awake()
    {
        _mainMenuPanelGO = FindPanel(MainMenuPanel);
        _pauseMenuPanelGO = FindPanel(PauseMenuPanel);
        _settingsPanelGO = FindPanel(SettingsPanel);

        ShowPanel(MainMenuPanel);
    }

    private static GameObject FindPanel(string panelName)
    {
        var panel = GameObject.Find(panelName);
        if (panel != null) return panel;

        foreach (var candidate in Resources.FindObjectsOfTypeAll<GameObject>())
            if (candidate.name == panelName && candidate.scene.IsValid())
                return candidate;

        return null;
    }

    public void ShowPanel(string panelName)
    {
        if (_mainMenuPanelGO != null)
            _mainMenuPanelGO.SetActive(panelName == MainMenuPanel);

        if (_pauseMenuPanelGO != null)
            _pauseMenuPanelGO.SetActive(panelName == PauseMenuPanel);

        if (_settingsPanelGO != null)
            _settingsPanelGO.SetActive(panelName == SettingsPanel);

        _currentPanel = panelName;
    }

    public void OnPlayPressed()
    {
        // TODO: Load your game scene here
        // Example: SceneManager.LoadScene("GameScene");
        Debug.Log("Play pressed — add your scene load logic");
    }

    public void OnSettingsPressed()
    {
        _settingsReturnPanel = _currentPanel == SettingsPanel ? MainMenuPanel : _currentPanel;
        ShowPanel(SettingsPanel);
    }

    public void OnQuitPressed()
    {
#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }

    public void OnResumePressed()
    {
        Time.timeScale = 1f;
        ShowPanel(string.Empty);
    }

    public void OnBackPressed()
    {
        ShowPanel(_settingsReturnPanel);
    }
}
