namespace UIPilot.Editor.Modules.ScriptSetup
{
    internal static class ScriptSetupContent
    {
        internal static class Paths
        {
            internal const string OutputAssetPath = "Assets/UIPilot_GameManager.cs";
        }

        internal static class Script
        {
            internal const string GeneratedHeader =
                "// ── Generated by UIPilot — safe to edit ────────────────────\n" +
                "// This file was created by UIPilot but belongs to you.\n" +
                "// Once you edit any On...Pressed method, UIPilot asks before\n" +
                "// it ever overwrites this file.\n" +
                "// ─────────────────────────────────────────────────────────────\n" +
                "\n";

            // Every object name below is a format argument supplied by
            // ScriptSetupModule from UIGeneratorContent, so the generator and the
            // script it writes can never disagree about a name:
            //   {0} {1} {2}  Main / Pause / Settings panel
            //   {3} {4}      volume value text, volume meter fill
            //   {5} {6}      fullscreen value text, quality value text
            //   {7} {8}      version footnote object, its "Version {0}" format
            //   {9} {10}     the words shown for fullscreen on / off
            //   {11}         the global shader property the scene layers read
            //   {12}         the Time Of Day field, named once below so the theme can set it
            internal const string Header =
                "using TMPro;\n" +
                "using UnityEngine;\n" +
                "\n" +
                "public class UIPilot_GameManager : MonoBehaviour\n" +
                "{{\n" +
                "    private const string MainMenuPanel = \"{0}\";\n" +
                "    private const string PauseMenuPanel = \"{1}\";\n" +
                "    private const string SettingsPanel = \"{2}\";\n" +
                "\n" +
                "    // Settings are remembered between runs under these PlayerPrefs keys.\n" +
                "    private const string VolumeKey = \"UIPilot.Volume\";\n" +
                "    private const string FullscreenKey = \"UIPilot.Fullscreen\";\n" +
                "    private const string QualityKey = \"UIPilot.Quality\";\n" +
                "\n" +
                "    private GameObject _mainMenuPanelGO;\n" +
                "    private GameObject _pauseMenuPanelGO;\n" +
                "    private GameObject _settingsPanelGO;\n" +
                "    private string _currentPanel;\n" +
                "    private string _settingsReturnPanel = MainMenuPanel;\n" +
                "\n" +
                "    private float _volume;\n" +
                "    private bool _fullscreen;\n" +
                "    private int _quality;\n" +
                "    private TMP_Text _volumeValue;\n" +
                "    private RectTransform _volumeFill;\n" +
                "    private TMP_Text _fullscreenValue;\n" +
                "    private TMP_Text _qualityValue;\n" +
                "\n" +
                "    [Header(\"Scene\")]\n" +
                "    [Tooltip(\"The hour the menu's scene shows, for themes that have one: 0 = midnight, 0.25 = dawn, 0.5 = noon, 0.75 = dusk. Change it from your code with SetTimeOfDay.\")]\n" +
                "    [Range(0f, 1f)] public float {12} = 0.5f;\n" +
                "\n" +
                "    [Tooltip(\"Seconds for one full day, when the scene should run on its own. 0 = it stays at Time Of Day.\")]\n" +
                "    public float dayLengthSeconds = 0f;\n" +
                "\n" +
                "    // The one value every scene layer reads; UIPilot's shader looks it up by this name.\n" +
                "    private const string TimeOfDayProperty = \"{11}\";\n" +
                "    private float _hourFrom, _hourStep, _hourBlend = 1f, _hourSeconds;\n" +
                "\n" +
                "    private void Awake()\n" +
                "    {{\n" +
                "        Shader.SetGlobalFloat(TimeOfDayProperty, timeOfDay);\n" +
                "\n" +
                "        _mainMenuPanelGO = FindObject(MainMenuPanel);\n" +
                "        _pauseMenuPanelGO = FindObject(PauseMenuPanel);\n" +
                "        _settingsPanelGO = FindObject(SettingsPanel);\n" +
                "\n" +
                "        _volumeValue = FindText(\"{3}\");\n" +
                "        _fullscreenValue = FindText(\"{5}\");\n" +
                "        _qualityValue = FindText(\"{6}\");\n" +
                "\n" +
                "        var fill = FindObject(\"{4}\");\n" +
                "        _volumeFill = fill != null ? fill.GetComponent<RectTransform>() : null;\n" +
                "\n" +
                "        // The main menu's small print always shows the build's real version.\n" +
                "        var version = FindText(\"{7}\");\n" +
                "        if (version != null) version.text = string.Format(\"{8}\", Application.version);\n" +
                "\n" +
                "        _volume = PlayerPrefs.GetFloat(VolumeKey, AudioListener.volume);\n" +
                "        _fullscreen = PlayerPrefs.GetInt(FullscreenKey, Screen.fullScreen ? 1 : 0) == 1;\n" +
                "        _quality = PlayerPrefs.GetInt(QualityKey, QualitySettings.GetQualityLevel());\n" +
                "        ApplySettings();\n" +
                "    }}\n" +
                "\n" +
                "    // Start, not Awake: the EventSystem must be running before a button can take focus.\n" +
                "    private void Start()\n" +
                "    {{\n" +
                "        ShowPanel(MainMenuPanel);\n" +
                "    }}\n" +
                "\n" +
                "    // Turns the scene's clock: a running day, or one blend asked for by SetTimeOfDay.\n" +
                "    // Unscaled time, so the scene keeps moving behind a pause menu.\n" +
                "    private void Update()\n" +
                "    {{\n" +
                "        if (dayLengthSeconds > 0f)\n" +
                "        {{\n" +
                "            timeOfDay = Mathf.Repeat(timeOfDay + Time.unscaledDeltaTime / dayLengthSeconds, 1f);\n" +
                "            _hourBlend = 1f;\n" +
                "        }}\n" +
                "        else if (_hourBlend < 1f)\n" +
                "        {{\n" +
                "            _hourBlend = Mathf.Min(1f, _hourBlend + Time.unscaledDeltaTime / _hourSeconds);\n" +
                "            var eased = _hourBlend * _hourBlend * (3f - 2f * _hourBlend);\n" +
                "            timeOfDay = Mathf.Repeat(_hourFrom + _hourStep * eased, 1f);\n" +
                "        }}\n" +
                "\n" +
                "        Shader.SetGlobalFloat(TimeOfDayProperty, timeOfDay);\n" +
                "    }}\n" +
                "\n" +
                "    // Sets the scene's hour (0 = midnight, 0.5 = noon), at once or blended over\n" +
                "    // some seconds, the short way round the clock. Call it from your own code:\n" +
                "    // FindAnyObjectByType<UIPilot_GameManager>().SetTimeOfDay(0.75f, 3f);\n" +
                "    public void SetTimeOfDay(float hour, float seconds = 0f)\n" +
                "    {{\n" +
                "        hour = Mathf.Repeat(hour, 1f);\n" +
                "        if (seconds <= 0f)\n" +
                "        {{\n" +
                "            timeOfDay = hour;\n" +
                "            _hourBlend = 1f;\n" +
                "            Shader.SetGlobalFloat(TimeOfDayProperty, timeOfDay);\n" +
                "            return;\n" +
                "        }}\n" +
                "\n" +
                "        _hourFrom = timeOfDay;\n" +
                "        _hourStep = Mathf.Repeat(hour - timeOfDay + 0.5f, 1f) - 0.5f;\n" +
                "        _hourSeconds = seconds;\n" +
                "        _hourBlend = 0f;\n" +
                "    }}\n" +
                "\n" +
                "    // Finds an object even when it, or its panel, is switched off.\n" +
                "    private static GameObject FindObject(string objectName)\n" +
                "    {{\n" +
                "        var found = GameObject.Find(objectName);\n" +
                "        if (found != null) return found;\n" +
                "\n" +
                "        foreach (var candidate in Resources.FindObjectsOfTypeAll<GameObject>())\n" +
                "            if (candidate.name == objectName && candidate.scene.IsValid())\n" +
                "                return candidate;\n" +
                "\n" +
                "        return null;\n" +
                "    }}\n" +
                "\n" +
                "    private static TMP_Text FindText(string objectName)\n" +
                "    {{\n" +
                "        var found = FindObject(objectName);\n" +
                "        return found != null ? found.GetComponent<TMP_Text>() : null;\n" +
                "    }}\n" +
                "\n" +
                "    public void ShowPanel(string panelName)\n" +
                "    {{\n" +
                "        if (_mainMenuPanelGO != null)\n" +
                "            _mainMenuPanelGO.SetActive(panelName == MainMenuPanel);\n" +
                "\n" +
                "        if (_pauseMenuPanelGO != null)\n" +
                "            _pauseMenuPanelGO.SetActive(panelName == PauseMenuPanel);\n" +
                "\n" +
                "        if (_settingsPanelGO != null)\n" +
                "            _settingsPanelGO.SetActive(panelName == SettingsPanel);\n" +
                "\n" +
                "        _currentPanel = panelName;\n" +
                "        FocusFirstButton();\n" +
                "    }}\n" +
                "\n" +
                "    // Keyboard and gamepad players need a starting point, so the first button\n" +
                "    // of whichever panel is showing takes focus. Mouse players are unaffected.\n" +
                "    private void FocusFirstButton()\n" +
                "    {{\n" +
                "        var eventSystem = UnityEngine.EventSystems.EventSystem.current;\n" +
                "        if (eventSystem == null) return;\n" +
                "\n" +
                "        GameObject panel = null;\n" +
                "        if (_currentPanel == MainMenuPanel) panel = _mainMenuPanelGO;\n" +
                "        else if (_currentPanel == PauseMenuPanel) panel = _pauseMenuPanelGO;\n" +
                "        else if (_currentPanel == SettingsPanel) panel = _settingsPanelGO;\n" +
                "\n" +
                "        var first = panel != null ? panel.GetComponentInChildren<UnityEngine.UI.Button>() : null;\n" +
                "        eventSystem.SetSelectedGameObject(first != null ? first.gameObject : null);\n" +
                "    }}\n" +
                "\n" +
                "    // Clamps, applies, saves and displays the three settings. Every settings\n" +
                "    // button changes one value and then calls this.\n" +
                "    private void ApplySettings()\n" +
                "    {{\n" +
                "        var qualityNames = QualitySettings.names;\n" +
                "        _volume = Mathf.Clamp01(Mathf.Round(_volume * 10f) / 10f);\n" +
                "        _quality = Mathf.Clamp(_quality, 0, Mathf.Max(0, qualityNames.Length - 1));\n" +
                "\n" +
                "        AudioListener.volume = _volume;\n" +
                "        Screen.fullScreen = _fullscreen;\n" +
                "        if (QualitySettings.GetQualityLevel() != _quality)\n" +
                "            QualitySettings.SetQualityLevel(_quality);\n" +
                "\n" +
                "        PlayerPrefs.SetFloat(VolumeKey, _volume);\n" +
                "        PlayerPrefs.SetInt(FullscreenKey, _fullscreen ? 1 : 0);\n" +
                "        PlayerPrefs.SetInt(QualityKey, _quality);\n" +
                "\n" +
                "        if (_volumeValue != null) _volumeValue.text = Mathf.RoundToInt(_volume * 100f) + \"%\";\n" +
                "        if (_volumeFill != null) _volumeFill.anchorMax = new Vector2(_volume, 1f);\n" +
                "        if (_fullscreenValue != null) _fullscreenValue.text = _fullscreen ? \"{9}\" : \"{10}\";\n" +
                "        if (_qualityValue != null && qualityNames.Length > 0) _qualityValue.text = qualityNames[_quality];\n" +
                "    }}\n" +
                "\n";
            internal const string Footer = "}\n";

            // Generic fallback body for any label without a bespoke implementation
            // below (e.g. custom/future buttons).
            internal const string MethodTemplate =
                "    public void On{0}Pressed()\n" +
                "    {{\n" +
                "        // TODO: implement {0} logic\n" +
                "        Debug.Log(\"{0} pressed — add your logic\");\n" +
                "    }}\n";

            internal const string PlayMethodBody =
                "        // TODO: Load your game scene here\n" +
                "        // Example: SceneManager.LoadScene(\"GameScene\");\n" +
                "        Debug.Log(\"Play pressed — add your scene load logic\");";

            // The guard matters: Settings buttons exist on the Main and Pause menus
            // even when no Settings panel was built, and showing a panel that is
            // not there would hide every menu with no way back.
            internal const string SettingsMethodBody =
                "        if (_settingsPanelGO == null)\n" +
                "        {\n" +
                "            Debug.LogWarning(\"UIPilot: this scene has no Settings panel. Tick Settings Menu in Tools > UIPilot, then click Build UI.\");\n" +
                "            return;\n" +
                "        }\n" +
                "\n" +
                "        _settingsReturnPanel = _currentPanel == SettingsPanel ? MainMenuPanel : _currentPanel;\n" +
                "        ShowPanel(SettingsPanel);";

            internal const string BackMethodBody =
                "        ShowPanel(_settingsReturnPanel);";

            internal const string ResumeMethodBody =
                "        Time.timeScale = 1f;\n" +
                "        ShowPanel(string.Empty);";

            internal const string QuitMethodBody =
                "#if UNITY_EDITOR\n" +
                "        UnityEditor.EditorApplication.isPlaying = false;\n" +
                "#else\n" +
                "        Application.Quit();\n" +
                "#endif";

            // Settings: each button changes one value; ApplySettings() does the rest.
            internal const string VolumeDownMethodBody =
                "        _volume -= 0.1f;\n" +
                "        ApplySettings();";

            internal const string VolumeUpMethodBody =
                "        _volume += 0.1f;\n" +
                "        ApplySettings();";

            internal const string FullscreenMethodBody =
                "        _fullscreen = !_fullscreen;\n" +
                "        ApplySettings();";

            internal const string QualityDownMethodBody =
                "        _quality--;\n" +
                "        ApplySettings();";

            internal const string QualityUpMethodBody =
                "        _quality++;\n" +
                "        ApplySettings();";
        }

        internal static class GameObjects
        {
            internal const string ManagerName = "UIPilot_GameManager";
            // The serialized field Apply Theme writes the theme's hour into.
            internal const string TimeOfDayField = "timeOfDay";
        }

        internal static class Messages
        {
            internal const string GameManagerIntact =
                "UIPilot: UIPilot_GameManager already exists and is intact — skipping script generation";
            internal const string GameObjectCreated =
                "UIPilot: UIPilot_GameManager GameObject created — " +
                "its component is attached automatically once the script has compiled.";
            internal const string FileWritten =
                "UIPilot: Script written to Assets/UIPilot_GameManager.cs";
            internal const string RegenerationCancelled =
                "UIPilot: Regeneration cancelled — UIPilot_GameManager.cs left untouched.";
        }

        internal static class Dialogs
        {
            internal const string CustomGameManagerTitle =
                "Custom GameManager Logic Detected";
            internal const string CustomGameManagerMessage =
                "UIPilot_GameManager.cs contains custom logic beyond the generated template. " +
                "Regenerating will overwrite it. Continue?";
            internal const string CustomGameManagerConfirm = "Overwrite";
            internal const string CustomGameManagerCancel  = "Cancel";
        }

        internal static class Undo
        {
            internal const string Action = "Generate GameManager";
        }
    }
}
