namespace UIPilot.Editor.Modules.ScriptSetup
{
    internal static class ScriptSetupContent
    {
        internal static class Paths
        {
            internal const string OutputAssetPath = "Assets/UIPilot_GameManager.cs";
        }

        internal static class Script
        {
            internal const string GeneratedHeader =
                "// ── Generated by UIPilot — safe to edit ────────────────────\n" +
                "// This file was created by UIPilot but belongs to you.\n" +
                "// UIPilot will not overwrite your changes on regenerate\n" +
                "// unless you run Quick Clear first.\n" +
                "// ─────────────────────────────────────────────────────────────\n" +
                "\n";

            // {0}/{1}/{2} are the MainMenu/PauseMenu/Settings panel name literals,
            // supplied by ScriptSetupModule from UIGeneratorContent's panel-naming
            // constants so this stays the single source of truth for panel names.
            internal const string Header =
                "using UnityEngine;\n" +
                "\n" +
                "public class UIPilot_GameManager : MonoBehaviour\n" +
                "{{\n" +
                "    private const string MainMenuPanel = \"{0}\";\n" +
                "    private const string PauseMenuPanel = \"{1}\";\n" +
                "    private const string SettingsPanel = \"{2}\";\n" +
                "\n" +
                "    private GameObject _mainMenuPanelGO;\n" +
                "    private GameObject _pauseMenuPanelGO;\n" +
                "    private GameObject _settingsPanelGO;\n" +
                "    private string _currentPanel;\n" +
                "    private string _settingsReturnPanel = MainMenuPanel;\n" +
                "\n" +
                "    private void Awake()\n" +
                "    {{\n" +
                "        _mainMenuPanelGO = FindPanel(MainMenuPanel);\n" +
                "        _pauseMenuPanelGO = FindPanel(PauseMenuPanel);\n" +
                "        _settingsPanelGO = FindPanel(SettingsPanel);\n" +
                "\n" +
                "        ShowPanel(MainMenuPanel);\n" +
                "    }}\n" +
                "\n" +
                "    private static GameObject FindPanel(string panelName)\n" +
                "    {{\n" +
                "        var panel = GameObject.Find(panelName);\n" +
                "        if (panel != null) return panel;\n" +
                "\n" +
                "        foreach (var candidate in Resources.FindObjectsOfTypeAll<GameObject>())\n" +
                "            if (candidate.name == panelName && candidate.scene.IsValid())\n" +
                "                return candidate;\n" +
                "\n" +
                "        return null;\n" +
                "    }}\n" +
                "\n" +
                "    public void ShowPanel(string panelName)\n" +
                "    {{\n" +
                "        if (_mainMenuPanelGO != null)\n" +
                "            _mainMenuPanelGO.SetActive(panelName == MainMenuPanel);\n" +
                "\n" +
                "        if (_pauseMenuPanelGO != null)\n" +
                "            _pauseMenuPanelGO.SetActive(panelName == PauseMenuPanel);\n" +
                "\n" +
                "        if (_settingsPanelGO != null)\n" +
                "            _settingsPanelGO.SetActive(panelName == SettingsPanel);\n" +
                "\n" +
                "        _currentPanel = panelName;\n" +
                "    }}\n" +
                "\n";

            internal const string Footer = "}\n";

            // Generic fallback body for any label without a bespoke implementation
            // below (e.g. custom/future buttons).
            internal const string MethodTemplate =
                "    public void On{0}Pressed()\n" +
                "    {{\n" +
                "        // TODO: implement {0} logic\n" +
                "        Debug.Log(\"{0} pressed — add your logic\");\n" +
                "    }}\n";

            internal const string PlayMethodBody =
                "        // TODO: Load your game scene here\n" +
                "        // Example: SceneManager.LoadScene(\"GameScene\");\n" +
                "        Debug.Log(\"Play pressed — add your scene load logic\");";

            internal const string SettingsMethodBody =
                "        _settingsReturnPanel = _currentPanel == SettingsPanel ? MainMenuPanel : _currentPanel;\n" +
                "        ShowPanel(SettingsPanel);";

            internal const string BackMethodBody =
                "        ShowPanel(_settingsReturnPanel);";

            internal const string ResumeMethodBody =
                "        Time.timeScale = 1f;\n" +
                "        ShowPanel(string.Empty);";

            internal const string QuitMethodBody =
                "#if UNITY_EDITOR\n" +
                "        UnityEditor.EditorApplication.isPlaying = false;\n" +
                "#else\n" +
                "        Application.Quit();\n" +
                "#endif";
        }

        internal static class GameObjects
        {
            internal const string ManagerName = "UIPilot_GameManager";
        }

        internal static class Messages
        {
            internal const string GameManagerIntact =
                "UIPilot: UIPilot_GameManager already exists and is intact — skipping script generation";
            internal const string AddComponentManually =
                "UIPilot: UIPilot_GameManager.cs written and compiled. " +
                "Add the UIPilot_GameManager component to the UIPilot_GameManager GameObject manually.";
            internal const string FileWritten =
                "UIPilot: Script written to Assets/UIPilot_GameManager.cs";
            internal const string RegenerationCancelled =
                "UIPilot: Regeneration cancelled — UIPilot_GameManager.cs left untouched.";
        }

        internal static class Dialogs
        {
            internal const string CustomGameManagerTitle =
                "Custom GameManager Logic Detected";
            internal const string CustomGameManagerMessage =
                "UIPilot_GameManager.cs contains custom logic beyond the generated template. " +
                "Regenerating will overwrite it. Continue?";
            internal const string CustomGameManagerConfirm = "Overwrite";
            internal const string CustomGameManagerCancel  = "Cancel";
        }

        internal static class Undo
        {
            internal const string Action = "Generate GameManager";
        }

        // Button labels with bespoke method bodies — keyed by label string.
        internal const string PlayLabel     = "Play";
        internal const string SettingsLabel = "Settings";
        internal const string BackLabel     = "Back";
        internal const string ResumeLabel   = "Resume";
        internal const string QuitLabel     = "Quit";
    }
}
